package com.snc.entity;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.hostip
     *
     * @mbggenerated
     */
    private String hostip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.servername
     *
     * @mbggenerated
     */
    private String servername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.rule
     *
     * @mbggenerated
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.watchtime
     *
     * @mbggenerated
     */
    private String watchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.jmxtime
     *
     * @mbggenerated
     */
    private Date jmxtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.server
     *
     * @mbggenerated
     */
    private String server;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.subsystem
     *
     * @mbggenerated
     */
    private String subsystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.severity
     *
     * @mbggenerated
     */
    private String severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.thread
     *
     * @mbggenerated
     */
    private String thread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.msgid
     *
     * @mbggenerated
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.machine
     *
     * @mbggenerated
     */
    private String machine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.txid
     *
     * @mbggenerated
     */
    private String txid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.contentid
     *
     * @mbggenerated
     */
    private String contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.timestamp
     *
     * @mbggenerated
     */
    private String timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.hostip
     *
     * @return the value of log.hostip
     *
     * @mbggenerated
     */
    public String getHostip() {
        return hostip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.hostip
     *
     * @param hostip the value for log.hostip
     *
     * @mbggenerated
     */
    public void setHostip(String hostip) {
        this.hostip = hostip == null ? null : hostip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.servername
     *
     * @return the value of log.servername
     *
     * @mbggenerated
     */
    public String getServername() {
        return servername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.servername
     *
     * @param servername the value for log.servername
     *
     * @mbggenerated
     */
    public void setServername(String servername) {
        this.servername = servername == null ? null : servername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.port
     *
     * @return the value of log.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.port
     *
     * @param port the value for log.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.title
     *
     * @return the value of log.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.title
     *
     * @param title the value for log.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.rule
     *
     * @return the value of log.rule
     *
     * @mbggenerated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.rule
     *
     * @param rule the value for log.rule
     *
     * @mbggenerated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.content
     *
     * @return the value of log.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.content
     *
     * @param content the value for log.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.watchtime
     *
     * @return the value of log.watchtime
     *
     * @mbggenerated
     */
    public String getWatchtime() {
        return watchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.watchtime
     *
     * @param watchtime the value for log.watchtime
     *
     * @mbggenerated
     */
    public void setWatchtime(String watchtime) {
        this.watchtime = watchtime == null ? null : watchtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.jmxtime
     *
     * @return the value of log.jmxtime
     *
     * @mbggenerated
     */
    public Date getJmxtime() {
        return jmxtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.jmxtime
     *
     * @param jmxtime the value for log.jmxtime
     *
     * @mbggenerated
     */
    public void setJmxtime(Date jmxtime) {
        this.jmxtime = jmxtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.date
     *
     * @return the value of log.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.date
     *
     * @param date the value for log.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.server
     *
     * @return the value of log.server
     *
     * @mbggenerated
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.server
     *
     * @param server the value for log.server
     *
     * @mbggenerated
     */
    public void setServer(String server) {
        this.server = server == null ? null : server.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.message
     *
     * @return the value of log.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.message
     *
     * @param message the value for log.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.subsystem
     *
     * @return the value of log.subsystem
     *
     * @mbggenerated
     */
    public String getSubsystem() {
        return subsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.subsystem
     *
     * @param subsystem the value for log.subsystem
     *
     * @mbggenerated
     */
    public void setSubsystem(String subsystem) {
        this.subsystem = subsystem == null ? null : subsystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.userid
     *
     * @return the value of log.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.userid
     *
     * @param userid the value for log.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.severity
     *
     * @return the value of log.severity
     *
     * @mbggenerated
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.severity
     *
     * @param severity the value for log.severity
     *
     * @mbggenerated
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.thread
     *
     * @return the value of log.thread
     *
     * @mbggenerated
     */
    public String getThread() {
        return thread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.thread
     *
     * @param thread the value for log.thread
     *
     * @mbggenerated
     */
    public void setThread(String thread) {
        this.thread = thread == null ? null : thread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.msgid
     *
     * @return the value of log.msgid
     *
     * @mbggenerated
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.msgid
     *
     * @param msgid the value for log.msgid
     *
     * @mbggenerated
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.machine
     *
     * @return the value of log.machine
     *
     * @mbggenerated
     */
    public String getMachine() {
        return machine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.machine
     *
     * @param machine the value for log.machine
     *
     * @mbggenerated
     */
    public void setMachine(String machine) {
        this.machine = machine == null ? null : machine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.txid
     *
     * @return the value of log.txid
     *
     * @mbggenerated
     */
    public String getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.txid
     *
     * @param txid the value for log.txid
     *
     * @mbggenerated
     */
    public void setTxid(String txid) {
        this.txid = txid == null ? null : txid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.contentid
     *
     * @return the value of log.contentid
     *
     * @mbggenerated
     */
    public String getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.contentid
     *
     * @param contentid the value for log.contentid
     *
     * @mbggenerated
     */
    public void setContentid(String contentid) {
        this.contentid = contentid == null ? null : contentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.timestamp
     *
     * @return the value of log.timestamp
     *
     * @mbggenerated
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.timestamp
     *
     * @param timestamp the value for log.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }
}