package com.snc.entity;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.hostip
     *
     * @mbggenerated
     */
    private String hostip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.servername
     *
     * @mbggenerated
     */
    private String servername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.rule
     *
     * @mbggenerated
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.watchtime
     *
     * @mbggenerated
     */
    private String watchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.jmxtime
     *
     * @mbggenerated
     */
    private Date jmxtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.hostip
     *
     * @return the value of message.hostip
     *
     * @mbggenerated
     */
    public String getHostip() {
        return hostip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.hostip
     *
     * @param hostip the value for message.hostip
     *
     * @mbggenerated
     */
    public void setHostip(String hostip) {
        this.hostip = hostip == null ? null : hostip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.servername
     *
     * @return the value of message.servername
     *
     * @mbggenerated
     */
    public String getServername() {
        return servername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.servername
     *
     * @param servername the value for message.servername
     *
     * @mbggenerated
     */
    public void setServername(String servername) {
        this.servername = servername == null ? null : servername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.port
     *
     * @return the value of message.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.port
     *
     * @param port the value for message.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.rule
     *
     * @return the value of message.rule
     *
     * @mbggenerated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.rule
     *
     * @param rule the value for message.rule
     *
     * @mbggenerated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.watchtime
     *
     * @return the value of message.watchtime
     *
     * @mbggenerated
     */
    public String getWatchtime() {
        return watchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.watchtime
     *
     * @param watchtime the value for message.watchtime
     *
     * @mbggenerated
     */
    public void setWatchtime(String watchtime) {
        this.watchtime = watchtime == null ? null : watchtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.jmxtime
     *
     * @return the value of message.jmxtime
     *
     * @mbggenerated
     */
    public Date getJmxtime() {
        return jmxtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.jmxtime
     *
     * @param jmxtime the value for message.jmxtime
     *
     * @mbggenerated
     */
    public void setJmxtime(Date jmxtime) {
        this.jmxtime = jmxtime;
    }
}