package com.snc.dao;

import com.snc.entity.Log;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    Log selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Log record);

    /**
     * 查询log列表
     * @param queryMap 查询条件集合
     * @return
     */
    List<Log> selectLogs(Map queryMap);

    /**
     * 查询log数量
     * @param queryMap
     * @return
     */
    int selectLogsCount(Map queryMap);

    /**
     * ip列表
     * @return
     */
    List<String> selectHostips();

    /**
     * 查询指定ip的端口列表
     * @param ip
     * @return
     */
    List<String> selectPortByIp(@Param("ip") String ip);
}