package com.snc.dao;

import com.snc.entity.Message;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface MessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    Message selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Message record);

    /**
     * 查询message列表
     * @param queryMap 查询条件集合
     * @return
     */
    List<Message> selectMessages(Map queryMap);

    /**
     * ip列表
     * @return
     */
    List<String> selectHostips();

    /**
     * 查询指定ip的端口列表
     * @param ip
     * @return
     */
    List<String> selectPortByIp(@Param("ip") String ip);

    /**
     * 查询val值列表
     * @return
     */
    List<Map<String, Object>> selectVals(Map queryMap);

    /**
     * 查询weblogic告警时间
     * @return
     */
    List<Map<String, Object>> selectVals_weblogic(Map queryMap);
}